### ISSUE TITLE
is the mathpresso port available?

### ISSUE THREAD

**Issue by darnocian** [dpethes/dasmjit#1]
This project is really interesting.
I noticed that asmjit has evolved quite a bit since this port. (I've actually used the c++ version a few times).
I saw mentioned in the forum post that there author ported mathpresso as an example. It would be useful as a way to see how everything is wired together. I've managed to get a few things working, but it is easier to read actual examples vs figuring out all the code.

thanks again.

**Comment by dpethes** [comment]
Hi, for mathpresso see https://gist.github.com/dpethes/12294f2626df7bfa66e4f05c6537a6dd . I assume it's working, but I never tried it (that's why it's not part of the repo).

**Comment by darnocian** [comment]
Thanks for the reference! 

I'll check it out.
